# Write SQL queries to perform the following tasks using the Sakila database:
USE sakila;

# List the number of films per category.
SELECT c.name AS category_name, COUNT(*) AS number_of_films
FROM category AS c
INNER JOIN film_category AS fc 
ON c.category_id = fc.category_id
GROUP BY c.name;

# Retrieve the store ID, city, and country for each store.
SELECT s.store_id, ci.city, co.country    
FROM store s
JOIN address a
ON s.address_id = a.address_id
JOIN city ci
ON a.city_id = ci.city_id
JOIN country co
ON ci.country_id = co.country_id;
    
# Calculate the total revenue generated by each store in dollars.
SELECT s.store_id, SUM(p.amount) AS total_revenue
FROM store AS s
JOIN staff AS sta 
ON s.store_id = sta.store_id
JOIN payment AS p 
ON sta.staff_id = p.staff_id
GROUP BY s.store_id;

# Determine the average running time of films for each category.

SELECT c.name, ROUND(AVG(f.length),2) AS avg_run_time
FROM film AS f
JOIN film_category AS fc
ON f.film_id = fc.film_id
JOIN category AS c
ON fc.category_id = c.category_id
GROUP BY c.name;





